---
sidebar: sidebar 
permalink: ai-policy.html 
---
= Richtlinie, die die Verwendung von KI-generierten Inhalten in der technischen Dokumentation von NetApp untersagt
:toc: macro
:hardbreaks:
:allow-uri-read: 
:toc: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Bei NetApp schätzen wir das Know-how unserer Mitarbeiter, Dienstleister und Partner bei der Erstellung, Veröffentlichung und Pflege präziser, relevanter und nützlicher technischer Dokumentationen für unsere Kunden. Wir glauben, dass die Verwendung von KI-generierten Inhalten diese Werte gefährden und die Integrität und Genauigkeit unserer Dokumentation untergraben kann. Daher hat NetApp die Richtlinie, die Veröffentlichung von KI-generierten Inhalten zu untersagen, die nicht durch einen Menschen verifiziert und validiert wurden. Dies gilt für alle auf docs.netapp.com veröffentlichten technischen Dokumentationen. Diese Richtlinie ähnelt und erweitert die Richtlinie von NetApp, die die Verwendung von Sprachmodellen zum Schreiben von Code für die verkauften Produkte untersagt.

Wir erwarten von allen Beitragenden zu NetAppDocs, dass sie sich an die folgende Richtlinie halten:

* Ohne menschliche Überprüfung und Validierung ist die Veröffentlichung von kundenbezogenen Dokumentationen (Verwendung von NetApp Produkten), die aus KI generiert werden, nicht gestattet. Dazu gehören schriftliche Materialien, Grafiken, Multimedia oder andere Materialien, die auf docs.netapp.com veröffentlicht werden. Alle auf docs.netapp.com veröffentlichten Inhalte müssen von den Erstellern menschlicher Inhalte überprüft und validiert werden.
* Ein Teil der Rolle des Content-Erstellers für docs.netapp.com ist die Einhaltung der Style- und Contributor-Guides. Dazu gehört es, über neueste Entwicklungen bei KI-generierten Inhalten und deren Auswirkungen auf die technische Dokumentation von NetApp auf dem Laufenden zu bleiben.
* Von allen Mitarbeitern, Auftragnehmern und Partnern wird erwartet, dass sie diese Richtlinie einhalten. Wiederholte Verstöße können zu ausgesetzten Autorenrechten führen.


NetAppDocs-Mitarbeiter sollten Folgendes beachten:

* Alle KI-basierten, inhaltsgenerierenden Technologien, die in Software eingebettet sind, die Sie auf Ihrem Arbeitscomputer installiert haben, einschließlich der Technologien wie Microsoft 365 Co-Pilot, senden Ihre Daten an das Unternehmen, das die assistive Technologie hostet. Fordern Sie eine solche Technologie nicht mit vertraulichen Inhalten des Unternehmens auf, einschließlich, aber nicht beschränkt auf Spezifikationen für unveröffentlichte Produktfunktionen.
* Verwenden Sie keine öffentlichen KI-Technologien, um technische Dokumentation für **bisher unveröffentlichte** Produkte, Produktversionen oder Funktionen innerhalb von Produkten zu erstellen oder zu bearbeiten.
* Das Copyright für neue technische Dokumentationen muss bei NetApp verbleiben und darf vor den offiziellen Produktveröffentlichungen und der entsprechenden Veröffentlichung der technischen Dokumentation nicht mit AIS außerhalb von NetApp geteilt werden.
* Senden Sie keine vertraulichen Dokumentationen, neuen Inhalte oder Inhalte, die nach 2021 geschrieben wurden, einschließlich URLs, an AI (ChatGPT oder andere Tools). Alle Informationen, die in ChatGPT eingespeist werden, werden Teil des Trainingsdatensatzes, der wiederum Eigentum von OpenAI wird und von ihnen und ihren Nutzern genutzt werden kann. Obwohl ein Großteil dieser Daten öffentlich zugänglich ist, wollen wir das Modell nicht auf unserem eigenen IP trainieren.

